// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUDsu1WKuqH65-P3qHvTSDIL2QNqGl_BA',
    appId: '1:539912887024:web:0fe250f8c4ce68ff3d0035',
    messagingSenderId: '539912887024',
    projectId: 'blue-dock',
    authDomain: 'blue-dock.firebaseapp.com',
    storageBucket: 'blue-dock.firebasestorage.app',
    measurementId: 'G-4GRYZ7EGLZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoLt_qhgTr41hDYuiIvgNMUrKrlIECEIs',
    appId: '1:539912887024:android:3788cb709903bae93d0035',
    messagingSenderId: '539912887024',
    projectId: 'blue-dock',
    storageBucket: 'blue-dock.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBv4y9DwxCMn7Oh_ipzT5H8TkGhovl661E',
    appId: '1:539912887024:ios:ef52a2f7c520e14f3d0035',
    messagingSenderId: '539912887024',
    projectId: 'blue-dock',
    storageBucket: 'blue-dock.firebasestorage.app',
    iosBundleId: 'com.example.bluedock',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBv4y9DwxCMn7Oh_ipzT5H8TkGhovl661E',
    appId: '1:539912887024:ios:ef52a2f7c520e14f3d0035',
    messagingSenderId: '539912887024',
    projectId: 'blue-dock',
    storageBucket: 'blue-dock.firebasestorage.app',
    iosBundleId: 'com.example.bluedock',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUDsu1WKuqH65-P3qHvTSDIL2QNqGl_BA',
    appId: '1:539912887024:web:be976e800a20bb053d0035',
    messagingSenderId: '539912887024',
    projectId: 'blue-dock',
    authDomain: 'blue-dock.firebaseapp.com',
    storageBucket: 'blue-dock.firebasestorage.app',
    measurementId: 'G-NVZ3K7HMKY',
  );
}
